services:
  user-service:
    build: ./user-service
    container_name: user-service-dev
    ports:
      - "8080:8080"
    volumes:
      - ./user-service:/app
    command: go run ./cmd/main.go
    env_file:
      - ./user-service/.env
    depends_on:
      - cassandra

  cassandra:
    image: cassandra:4.0
    container_name: cassandra-db
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=DevCluster
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_START_RPC=true
